name: CI/CD to WildFly

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Set up Java (adjust version if needed)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build WAR using Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Step 4: Copy WAR to EC2
      - name: Upload WAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: target/sample-app.war
          target: /tmp/

      # Step 5: Deploy to WildFly
      - name: Deploy WAR to WildFly
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Switching to wildfly user..."
            sudo -u wildfly bash <<'EOF'
            if ! pgrep -u wildfly -f "wildfly" > /dev/null; then
              echo "WildFly not running, starting..."
              nohup /opt/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0 \
                > /opt/wildfly/wildfly.log 2>&1 &
              sleep 20
            fi

            echo "Cleaning old deployments..."
            rm -f /opt/wildfly/standalone/deployments/sample-app.war*

            echo "Copying new WAR..."
            cp /tmp/sample-app.war /opt/wildfly/standalone/deployments/

            echo "Waiting for management port..."
            timeout=60
            elapsed=0
            while ! ss -ltn | grep -q ":9990"; do
              sleep 2
              elapsed=$((elapsed + 2))
              if [ $elapsed -ge $timeout ]; then
                echo "ERROR: WildFly mgmt port not available"
                exit 1
              fi
            done

            echo "Verifying deployment..."
            /opt/wildfly/bin/jboss-cli.sh --connect --command="deployment-info"
            EOF
