name: Deploy to WildFly

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Set up Java (Maven build)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. Build WAR with Maven
      - name: Build WAR
        run: mvn clean package -DskipTests

      # 4. Verify WAR exists
      - name: Verify WAR built
        run: ls -lh target

      # 5. Upload WAR to EC2 (/tmp directly, no extra folder)
      - name: Upload WAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.JBOSS1 }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: target/sample-app.war
          target: /tmp/

      # 6. Deploy to WildFly (copy WAR into deployments)
      - name: Deploy WAR on WildFly
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.JBOSS1 }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "===== Starting WildFly if not running ====="
            if ! pgrep -u wildfly -f "wildfly" > /dev/null; then
              sudo -u wildfly nohup /opt/wildfly/bin/standalone.sh -b 0.0.0.0 \
                > /opt/wildfly/wildfly.log 2>&1 &
              sleep 20
            fi

            echo "===== Cleaning old deployments ====="
            sudo rm -f /opt/wildfly/standalone/deployments/sample-app.war.undeployed
            sudo touch /opt/wildfly/standalone/deployments/sample-app.war.dodeploy


            echo "===== Copying new WAR ====="
            sudo cp -r /tmp/sample-app.war /opt/wildfly/standalone/deployments/sample-app.war
            sudo chown wildfly:wildfly /opt/wildfly/standalone/deployments/sample-app.war

            echo "===== Deployment done. Check logs if needed ====="
            tail -n 20 /opt/wildfly/wildfly.log
