name: CI/CD Sample App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Build the WAR with Maven
      - name: Build WAR
        run: mvn clean package -DskipTests

      # 3️⃣ Copy WAR to EC2 Node1
      - name: Copy WAR to Node1
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.JBOSS1 }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: "target/sample-app.war"
          target: "/tmp/sample.war"

      # 4️⃣ Copy WAR to EC2 Node2
      - name: Copy WAR to Node2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.JBOSS2 }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: "target/sample-app.war"
          target: "/tmp/sample.war"

      # 5️⃣ Deploy WAR to Node1
      - name: Deploy WAR on Node1
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.JBOSS1 }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Start WildFly if not running
            if ! pgrep -u ec2-user -f "wildfly" > /dev/null; then
              echo "WildFly not running, starting with nohup..."
              nohup /opt/wildfly/bin/standalone.sh -b 0.0.0.0 > /opt/wildfly/standalone/log/nohup.log 2>&1 &
              sleep 15
            fi

            # Verify port 9990
            if ! ss -ltnp | grep -q ":9990"; then
              echo "ERROR: WildFly is not listening on port 9990"
              exit 1
            fi

            # Deploy the WAR
            /opt/wildfly/bin/jboss-cli.sh --connect "deploy /tmp/sample.war --force"

      # 6️⃣ Deploy WAR to Node2
      - name: Deploy WAR on Node2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.JBOSS2 }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Start WildFly if not running
            if ! pgrep -u ec2-user -f "wildfly" > /dev/null; then
              echo "WildFly not running, starting with nohup..."
              nohup /opt/wildfly/bin/standalone.sh -b 0.0.0.0 > /opt/wildfly/standalone/log/nohup.log 2>&1 &
              sleep 15
            fi

            # Verify port 9990
            if ! ss -ltnp | grep -q ":9990"; then
              echo "ERROR: WildFly is not listening on port 9990"
              exit 1
            fi

            # Deploy the WAR
            /opt/wildfly/bin/jboss-cli.sh --connect "deploy /tmp/sample.war --force"
