name: CI/CD Sample App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Build the WAR with Maven
      - name: Build WAR
        run: mvn clean package -DskipTests

      # 3️⃣ Copy WAR to EC2 Node1
      - name: Copy WAR to Node1
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.JBOSS1 }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: "target/sample-app.war"
          target: "/tmp/"

      # 4️⃣ Copy WAR to EC2 Node2
      - name: Copy WAR to Node2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.JBOSS2 }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: "target/sample-app.war"
          target: "/tmp/"

      # 5️⃣ Deploy WAR on Node1
      - name: Deploy WAR on Node1
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.JBOSS1 }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo -u wildfly bash <<'EOF'
            if ! pgrep -u wildfly -f "wildfly" > /dev/null; then
              echo "WildFly not running, starting..."
              nohup /opt/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0 \
                > /opt/wildfly/wildfly.log 2>&1 &
              sleep 20
            fi
            # Deploy WAR (must be a file, not dir)
            /opt/wildfly/bin/jboss-cli.sh --connect \
              --command="deploy /tmp/sample-app.war --force"
            EOF

      # 6️⃣ Deploy WAR on Node2
      - name: Deploy WAR on Node2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.JBOSS2 }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo -u wildfly bash <<'EOF'
            if ! pgrep -u wildfly -f "wildfly" > /dev/null; then
              echo "WildFly not running, starting..."
              nohup /opt/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0 \
                > /opt/wildfly/wildfly.log 2>&1 &
              sleep 20
            fi
            # Deploy WAR (must be a file, not dir)
            /opt/wildfly/bin/jboss-cli.sh --connect \
              --command="deploy /tmp/sample-app.war --force"
            EOF
