name: Deploy to WildFly on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload WAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: target/sample-app.war
          target: /tmp/sample-app.war

      - name: Deploy on WildFly
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          envs: WILDFLY_USER,WILDFLY_PASS
          script: |
            echo "Fixing permissions..."
            sudo chown -R wildfly:wildfly /opt/wildfly/standalone

            if ! pgrep -u wildfly -f "wildfly" > /dev/null; then
              echo "Starting WildFly..."
              sudo -u wildfly nohup /opt/wildfly/bin/standalone.sh \
                -b 0.0.0.0 -bmanagement 0.0.0.0 \
                > /opt/wildfly/wildfly.log 2>&1 &
              sleep 20
            fi

            echo "Cleaning old deployments..."
            sudo -u wildfly rm -f /opt/wildfly/standalone/deployments/sample-app.war*

            echo "Copying new WAR..."
            sudo cp /tmp/sample-app.war /opt/wildfly/standalone/deployments/sample-app.war
            sudo chown wildfly:wildfly /opt/wildfly/standalone/deployments/sample-app.war

            echo "Deploying via CLI..."
            sudo -u wildfly /opt/wildfly/bin/jboss-cli.sh \
              --connect \
              --controller=127.0.0.1:9990 \
              --user=$WILDFLY_USER \
              --password=$WILDFLY_PASS \
              --command="deploy /opt/wildfly/standalone/deployments/sample-app.war --force"

            echo "Verifying deployment..."
            sudo -u wildfly /opt/wildfly/bin/jboss-cli.sh \
              --connect \
              --controller=127.0.0.1:9990 \
              --user=$WILDFLY_USER \
              --password=$WILDFLY_PASS \
              --command="deployment-info"
        env:
          WILDFLY_USER: ${{ secrets.WILDFLY_USER }}
          WILDFLY_PASS: ${{ secrets.WILDFLY_PASS }}
