name: CI/CD Sample App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Build the WAR with Maven
      - name: Build WAR
        run: mvn clean package -DskipTests

      # 3️⃣ Copy WAR to EC2 Node1
      - name: Copy WAR to Node1
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.JBOSS1 }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: "target/sample-app.war"
          target: "/tmp/sample.war"

      # 4️⃣ Copy WAR to EC2 Node2
      - name: Copy WAR to Node2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.JBOSS2 }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: "target/sample-app.war"
          target: "/tmp/sample.war"

      # 5️⃣ Deploy WAR on Node1
      - name: Deploy WAR on Node1
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.JBOSS1 }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Ensure WildFly is running
            if ! systemctl is-active --quiet wildfly; then
              echo "WildFly not running, starting..."
              sudo systemctl start wildfly
              sleep 10
            fi

            # Deploy the WAR as wildfly user
            sudo -u wildfly /opt/wildfly/bin/jboss-cli.sh --connect "deploy /tmp/sample.war --force"

      # 6️⃣ Deploy WAR on Node2
      - name: Deploy WAR on Node2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.JBOSS2 }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Ensure WildFly is running
            if ! systemctl is-active --quiet wildfly; then
              echo "WildFly not running, starting..."
              sudo systemctl start wildfly
              sleep 10
            fi

            # Deploy the WAR as wildfly user
            sudo -u wildfly /opt/wildfly/bin/jboss-cli.sh --connect "deploy /tmp/sample.war --force"
