name: CI/CD WildFly Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Java
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Build WAR with Maven (adjust if using Gradle)
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Upload WAR to EC2
      - name: Upload WAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: target/sample-app.war
          target: /tmp/

      # Deploy WAR on WildFly
      - name: Deploy to WildFly
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo -u wildfly bash <<'EOF'
            if ! pgrep -u wildfly -f "wildfly" > /dev/null; then
              echo "[INFO] WildFly not running, starting..."
              touch /opt/wildfly/wildfly.log
              chmod 664 /opt/wildfly/wildfly.log
              chown wildfly:wildfly /opt/wildfly/wildfly.log
              nohup /opt/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0 \
                > /opt/wildfly/wildfly.log 2>&1 &
              sleep 10
            fi

            echo "[INFO] Waiting for WildFly management port..."
            timeout=120
            elapsed=0
            while ! ss -ltn | grep -q ":9990"; do
              sleep 2
              elapsed=$((elapsed + 2))
              if [ $elapsed -ge $timeout ]; then
                echo "[ERROR] WildFly mgmt port not available after $timeout seconds"
                exit 1
              fi
            done
            echo "[INFO] WildFly management port is up."

            echo "[INFO] Cleaning old deployments..."
            rm -f /opt/wildfly/standalone/deployments/sample-app.war*

            echo "[INFO] Copying new WAR..."
            cp /tmp/sample-app.war /opt/wildfly/standalone/deployments/

            echo "[INFO] Verifying deployment..."
            /opt/wildfly/bin/jboss-cli.sh --connect --command="deployment-info"
            EOF
