name: CI/CD Sample App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Build the WAR with Maven
      - name: Build WAR
        run: mvn clean package -DskipTests

      # 3️⃣ Copy WAR to EC2 Node1
      - name: Copy WAR to Node1
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.JBOSS1 }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: "target/sample-app.war"
          target: "/tmp/sample.war"

      # 4️⃣ Copy WAR to EC2 Node2
      - name: Copy WAR to Node2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.JBOSS2 }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: "target/sample-app.war"
          target: "/tmp/sample.war"

      # 5️⃣ Deploy WAR to Node1 via SSH
      - name: Deploy WAR on Node1
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.JBOSS1 }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Check if WildFly is running, if not start it
            if ! pgrep -u wildfly -f "wildfly" > /dev/null; then
              echo "WildFly not running on Node1, starting..."
              sudo -u wildfly /opt/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0 &
              sleep 10
            fi
            sudo -u wildfly /opt/wildfly/bin/jboss-cli.sh --connect "deploy /tmp/sample.war --force"

      # 6️⃣ Deploy WAR to Node2 via SSH
      - name: Deploy WAR on Node2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.JBOSS2 }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Check if WildFly is running, if not start it
            if ! pgrep -u wildfly -f "wildfly" > /dev/null; then
              echo "WildFly not running on Node2, starting..."
              sudo -u wildfly /opt/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0 &
              sleep 10
            fi
            sudo -u wildfly /opt/wildfly/bin/jboss-cli.sh --connect "deploy /tmp/sample.war --force"
