name: Deploy to WildFly

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. Build WAR with Maven
      - name: Build WAR
        run: mvn clean package -DskipTests

      # 4. Debug WAR path (optional but useful)
      - name: Debug WAR path
        run: ls -R target || true

      # 5. Upload WAR to EC2
      - name: Upload WAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.JBOSS1 }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          # support multi-module projects
          source: "**/target/*.war"
          target: /tmp/

      # 6. Deploy to WildFly
      - name: Deploy WAR on WildFly
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.JBOSS1 }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          envs: WILDFLY_USER,WILDFLY_PASS
          script: |
            sudo -u wildfly bash <<'EOF'
